pip3.8 install --user cycler
pip3.8 install --user decorator
pip3.8 install --user imageio
pip3.8 install --user joblib
pip3.8 install --user kiwisolver
pip3.8 install --user mahotas
pip3.8 install --user matplotlib
pip3.8 install --user networkx
pip3.8 install --user Pillow
pip3.8 install --user pip
pip3.8 install --user pyparsing
pip3.8 install --user python-dateutil
pip3.8 install --user PyWavelets
pip3.8 install --user root-numpy
pip3.8 install --user scikit-image
pip3.8 install --user scikit-learn
pip3.8 install --user scipy
pip3.8 install --user setuptools
pip3.8 install --user six
pip3.8 install --user sklearn
pip3.8 install --user threadpoolctl
pip3.8 install --user tifffile
